# Generated by Django 2.2.19 on 2023-02-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'Реакция', 'verbose_name_plural': 'Реакции'},
        ),
    ]
